[package]
edition = "2021"
name = "platform"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.3"
anyhow = "1.0.57"
wasi-common = "0.36.0"
wasmtime = "0.36.0"
wasmtime-wasi = "0.36.0"
